Allow for empty aliases
YAML doesn't support empty hashes

If `aliases` is given no hash, the xmpp client will throw an error:

  File "./pushmanager/core/xmppclient.py", line 56, in
  _process_queue_item
      recipient = Settings['aliases'].get(recipient, recipient)
      AttributeError: 'NoneType' object has no attribute 'get'